### PR TITLE
Initial project setup

### LINKED ISSUE #1: Initial project setup
setup project with react and vite

### PR DESCRIPTION
**Pull request by principalkelvo**
Fixes #1
 creates a scaffold from a react-vite template
 uses latest vite
 uses Javascript

# Description

This PR includes the initial setup for a React-Vite blog application. It creates a scaffold from a react-vite template using the latest version of Vite and JavaScript.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This initial setup does not require any tests.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Note: Some of the checklist items might not be applicable to this PR since it's just an initial setup.

### CODE REVIEW

**Review by JimmyTron — APPROVED** [review]

**Comment by nyandika** [comment]
Is there argument against using typescript for this?

**Comment by jumalaw98** [comment]
@principalkelvo why vite than typescript or normal js?

**Review by leroy-netizen — APPROVED** [review]
This looks good. Is it possible we dockerize it? To standardize the working environment that is.

**Comment by principalkelvo** [comment]
> @principalkelvo why vite than typescript or normal js? 

I initialised the app to use normal Javascript,but we will have to change to typescript because most of the members use typescript. Vite is a tool to load the project faster (instant server, and optimizing build)

**Comment by principalkelvo** [comment]
> This looks good. Is it possible we dockerize it? To standardize the working environment that is.

Yes it's possible, you can dockerize it.

**Comment by nyandika** [comment]
@leroy-netizen @principalkelvo Can we please not straight up merge PRs until the discussions in them are resolved at least

**Comment by leroy-netizen** [comment]
> @leroy-netizen @principalkelvo Can we please not straight up merge PRs until the discussions in them are resolved at least

Sure. That was wrong for me to do. Will check on it next time. Thanks

**Pull request merged**
